#Both the Deployment and Service are in this file, cause the belong together
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mongoDB
        image: mongo:7.0.7-jammy
        ports:
        - containerPort: 27017
