apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp

spec:
  replicas: 1
  selector: 
    matchLabels:
      app: webapp
      #configuration for pods
  template: 
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0
        resources: 
          limits:
            cpu: "1"
            memory: "512Mi"
          requests:  
            cpu: "0.5"
            memory: "256Mi"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: service
metadata:
  name: webapp-service
spec:
  selector: 
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
    
     
